apps/qd/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField
from wtforms.validators import DataRequired


class QdForm(FlaskForm):
    stage = StringField('阶段',validators=[DataRequired()])  # 阶段
    progress = StringField('进度',validators=[DataRequired()])  # 进度
    code_num = IntegerField('代码数',validators=[DataRequired()])  # 代码数
    bug_num = IntegerField('bug数',validators=[DataRequired()])  # bug数
    create_time = StringField('日期',validators=[DataRequired()])
    remarks = StringField()

apps/__init__.py
from flask import Flask
from apps import config

from flask_wtf import CSRFProtect

app = Flask(__name__)
app.config.from_object(config)

CSRFProtect(app)

from apps.user import user

app.register_blueprint(user)

from apps.qd import qd

app.register_blueprint(qd)


from logging.config import dictConfig

dictConfig({
    'version': 1,
    'formatters': {'default': {
        'format': '[%(asctime)s] %(levelname)s in %(module)s: %(message)s',
    }},
    'handlers': {'wsgi': {
        'class': 'logging.StreamHandler',
        'stream': 'ext://flask.logging.wsgi_errors_stream',
        'formatter': 'default'
    }},
    'root': {
        'level': 'INFO',
        'handlers': ['wsgi']
    }
})

from apps import filter
from flask_restful import Api

api = Api(app)
from apps.clazz import clazz
app.register_blueprint(clazz)

apps/clazz/__init__.py
from flask import Blueprint

clazz = Blueprint('clazz',__name__,url_prefix='/clazz')

from . import view

apps/qd/__init__.py
from flask import Blueprint

qd = Blueprint('qd',__name__)

from apps.qd import view

apps/user/__init__.py
from flask import Blueprint

user = Blueprint('user', __name__)

from apps.user import views

apps/user/views.py
import functools

from apps.user import user
from flask import render_template, request, redirect, url_for, session,flash,jsonify,current_app
from apps.model import User, db, Clazz
from flask.views import MethodView
from apps.decorators import login_required


@user.route('/index/')
@login_required
def index():
    return render_template('home.html')


@user.route('/login/', methods=['GET', 'POST'])
def login():
    if 'GET' == request.method:
        return render_template('login.html')
    else:
        uname = request.form['uname']
        passwd = request.form['passwd']
        current_app.logger.info('{}：在尝试登录'.format(uname))
        user = User.query.filter_by(uname=uname).first()
        if user:
            if user.check_password(passwd):
                current_app.logger.info('{}：登录成功了'.format(uname))
                session['uid'] = user.id
                session['uname'] = user.uname
                session['nick'] = user.nick_name
                session['sex'] = user.sex
                return redirect(url_for('user.index'))
            else:
                flash('密码错误')
                return render_template('login.html', msg='密码错误')
        else:
            flash('用户名不存在！')
            return render_template('login.html', msg='用户名不存在')


@user.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('user.login'))


class RegisterView(MethodView):

    def get(self):
        clazz = Clazz.query.all()
        return render_template('register.html', clazz=clazz)

    def post(self):
        uname = request.form['uname']
        passwd = request.form['passwd']
        real_passwd = request.form['real_passwd']
        nick_name = request.form['nick_name']
        sex = request.form['sex']
        phone = request.form['phone']
        cid = request.form['cid']
        user = User.query.filter_by(uname=uname).first()
        if user:
            return render_template('register.html', msg='用户名已存在')
        else:
            user = User(uname, passwd, nick_name, sex, phone, cid)
            clazz = Clazz.query.filter_by(id=cid).first()
            user.clazzs.append(clazz)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('user.login'))


class PersonalView(MethodView):
    decorators = [login_required]

    def get(self):
        clazz = Clazz.query.all()
        user = User.query.filter_by(id=session['uid']).first()
        return render_template('user/personal.html', user=user, clazz=clazz)

    def post(self):
        uname = request.form['uname']
        nick_name = request.form['nick_name']
        sex = request.form['sex']
        phone = request.form['phone']
        cid = request.form['cid']
        user = User.query.filter_by(id=session['uid']).first()
        if user:
            user.uname = uname
            user.nick_name = nick_name
            user.sex = sex
            user.phone = phone
            user.cid = cid
            db.session.commit()
        return redirect(url_for('user.personal'))


@user.route('/get_user/')
@user.route('/get_user/<int:page>')
def get_user(page=1):
    pager = User.query.paginate(page,2)
    clazzs = Clazz.query.all()
    return render_template('user/manager.html', pager=pager, clazzs=clazzs)

@user.route('/reset_pwd/<int:uid>/')
def reset_pwd(uid=None):
    if uid:
        user =User.query.filter_by(id=uid).first()
        if user:
            user.passwd='123'
            db.session.commit()
    return redirect(url_for('user.get_user'))

@user.route('/change_user/',methods=['GET','POST'])
def change_user():
    data = request.form
    user = User.query.filter_by(id = data.get('uid')).first()
    user.rid = data.get('rid')
    user.nick_name = data.get('nick_name')
    user.sex = data.get('sex')
    user.clazzs = Clazz.query.filter_by(id = data.get('cid')).all()
 
    db.session.commit()
    return jsonify({'status':'1','msg':'更新成功！'})
    

# 通过add_url_rule添加类视图和url的映射，并且在as_view方法中指定该url的名称，方便url_for函数调用
user.add_url_rule('/register/', view_func=RegisterView.as_view('register'))
user.add_url_rule('/personal/', view_func=PersonalView.as_view('personal'))

apps/templates/clazz/index.html
{% extends '/common/index_base.html'%}
{% block title%}
班级管理
{% endblock%}
{% block panel_title%}
班级管理
{% endblock%}
{% block info %}
<div class="content-row">
    <form>
        <div class="form-group col-md-3">
            <div class="col-md-3 "><label class="control-label">编号：</label></div>
            <div class="col-md-9"><input id="cno" type="text" class="form-control" placeholder="编号">
            </div>
        </div>
        <div class="form-group col-md-3">
            <div class="col-md-3"><label class="control-label">名称：</label></div>
            <div class="col-md-9"><input id="cname" type="text" class="form-control" placeholder="名称">
            </div>
        </div>
        <div class="form-group col-md-3">
            <div class="col-md-3">
                <label class="control-label">人数：</label>
            </div>
            <div class="col-md-4">
                <input name="min" type="text" class="col-md-3 form-control" placeholder="大于">
            </div>
            <div class="col-md-4">
                <input name="max" type="text" class="col-md-3 form-control" placeholder="小于"">
        </div>
    </div>
        <div class=" form-group col-md-3">
                <input type="button" class="btn btn-primary" value="查 询" onclick="do_search()">
                <input id="reset" type="button" class="btn btn-info" value="重 置">
            </div>
    </form>
</div>
<div class="content-row">
    <button type="button" class="btn btn-info btn-block" data-toggle="tooltip" data-placement="top" title=""
        data-original-title="Tooltip on top">班级信息
    </button>
    <table class="table table-bordered">

        <tr>
            <td>编号</td>
            <td>名称</td>
            <td>人数</td>
            <td>操作</td>
        </tr>
    </table>
</div>
{% endblock%}
{% block script %}
<script>
    $(function(){
        init_data()
    })
    function init_data(){
        $.ajax({
            url:"/clazz_list",
            method:"get",
            success:function(rs){
                for(var i = 0; i< rs.length;i++){
                    trs = '<tr><td>'+rs[i].id+'</td><td><input type="text" class="form-control" value="'+rs[i].name+'"/></td><td><input type="text" class="form-control" value="'+rs[i].count+'"/></td><td><input type="button" class="btn btn-primary" value="提 交" onclick="do_update()"></td></tr>'
                    $('table').append(trs)
                }
           
            }
        })
    }
</script>
{% endblock %}

apps/templates/common/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no">

    <!-- site css -->
    <link rel="stylesheet" href="{{ url_for('static',filename='dist/css/site.min.css') }}">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
    <!--[if lt IE 9]>
      <script src="{{ url_for('static',filename='js/html5shiv.js') }}"></script>
      <script src="{{ url_for('static',filename='js/respond.min.js') }}"></script>
    <![endif]-->
    <script type="text/javascript" src="{{ url_for('static',filename='dist/js/site.min.js') }}"></script>
    {% block head %}
    {% endblock %}
</head>

<body>
{% block container %}
{% endblock %}
</body>
{% block script %}
{% endblock %}
</html>

apps/templates/common/index_base.html
{% extends '/common/base.html' %}
{% block container %}
    <!--nav-->
    <nav role="navigation" class="navbar navbar-custom">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">

                <a href="#" class="navbar-brand">Feelings's System</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div id="bs-content-row-navbar-collapse-5" class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            {% if session.nick %}
                                {{session.nick}}
                            {% endif %}
                            <b class="caret"></b>
                        </a>
                        <ul role="menu" class="dropdown-menu">
                            <li class="dropdown-header">Setting</li>
                            <li><a href="#">Action</a></li>
                            <li class="divider"></li>
                            <li class="active"><a href="#">Separated link</a></li>
                            <li class="divider"></li>
                            <li class="disabled"><a href="{{ url_for('user.logout') }}">Signout</a></li>
                        </ul>
                    </li>
                </ul>

            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
    <!--header-->
    <div class="container-fluid">
        <!--documents-->
        <div class="row row-offcanvas row-offcanvas-left">
            <div class="col-xs-6 col-sm-3 sidebar-offcanvas" role="navigation">
                <ul class="list-group panel">
                        <li class="list-group-item"><i class="glyphicon glyphicon-align-justify"></i> <b>功能菜单</b></li>
                    <li class="list-group-item"><input type="text" class="form-control search-query"
                                                       placeholder="Search Something"></li>
                    <li class="list-group-item"><a href="{{ url_for('user.index') }}"><i class="glyphicon glyphicon-home"></i>个人主页
                    </a></li>
                    <li class="list-group-item"><a href="{{ url_for('user.personal') }}"><i class="glyphicon glyphicon-user"></i>个人信息
                    </a></li>
                       <li class="list-group-item"><a href="{{ url_for('qd.qd') }}"><i class="glyphicon glyphicon-bell"></i>个人签到</a>
                    <li class="list-group-item"><a href="{{ url_for('user.get_user')}}"><i class="glyphicon glyphicon-certificate"></i>用户管理
                    </a></li>
                    <li class="list-group-item"><a href="{{ url_for('clazz.index')}}"><i class="glyphicon glyphicon-th-list"></i>班级管理
                    </a></li>
                    <li class="list-group-item"><a href="forms.html"><i
                            class="glyphicon glyphicon-list-alt"></i>Forms</a></li>

                    </li>
                    <li class="list-group-item"><a href="timeline.html"><i class="glyphicon glyphicon-indent-left"></i>Timeline</a>
                    </li>
                    <li class="list-group-item"><a href="calendars.html"><i class="glyphicon glyphicon-calendar"></i>Calendars</a>
                    </li>
                    <li class="list-group-item"><a href="typography.html"><i class="glyphicon glyphicon-font"></i>Typography</a>
                    </li>
                    <li class="list-group-item"><a href="footers.html"><i class="glyphicon glyphicon-minus"></i>Footers</a>
                    </li>
                    <li class="list-group-item"><a href="panels.html"><i class="glyphicon glyphicon-list-alt"></i>Panels</a>
                    </li>
                    <li class="list-group-item"><a href="navs.html"><i class="glyphicon glyphicon-th-list"></i>Navs</a>
                    </li>
                    <li class="list-group-item"><a href="colors.html"><i class="glyphicon glyphicon-tint"></i>Colors</a>
                    </li>
                    <li class="list-group-item"><a href="flex.html"><i class="glyphicon glyphicon-th"></i>Flex</a></li>
                    <li class="list-group-item"><a href="../login.html"><i class="glyphicon glyphicon-lock"></i>Login</a>
                    </li>
                    <li>
                        <a href="#demo3" class="list-group-item " data-toggle="collapse">Item 3 <span
                                class="glyphicon glyphicon-chevron-right"></span></a>
                        <div class="collapse" id="demo3">
                            <a href="#SubMenu1" class="list-group-item" data-toggle="collapse">Subitem 1 <span
                                    class="glyphicon glyphicon-chevron-right"></span></a>
                            <div class="collapse list-group-submenu" id="SubMenu1">
                                <a href="#" class="list-group-item">Subitem 1 a</a>
                                <a href="#" class="list-group-item">Subitem 2 b</a>
                                <a href="#SubSubMenu1" class="list-group-item" data-toggle="collapse">Subitem 3 c <span
                                        class="glyphicon glyphicon-chevron-right"></span></a>
                                <div class="collapse list-group-submenu list-group-submenu-1" id="SubSubMenu1">
                                    <a href="#" class="list-group-item">Sub sub item 1</a>
                                    <a href="#" class="list-group-item">Sub sub item 2</a>
                                </div>
                                <a href="#" class="list-group-item">Subitem 4 d</a>
                            </div>
                            <a href="javascript:;" class="list-group-item">Subitem 2</a>
                            <a href="javascript:;" class="list-group-item">Subitem 3</a>
                        </div>
                    </li>
                    <li>
                        <a href="#demo4" class="list-group-item " data-toggle="collapse">Item 4 <span
                                class="glyphicon glyphicon-chevron-right"></span></a>
                    <li class="collapse" id="demo4">
                        <a href="" class="list-group-item">Subitem 1</a>
                        <a href="" class="list-group-item">Subitem 2</a>
                        <a href="" class="list-group-item">Subitem 3</a>
                    </li>
                    </li>
                </ul>
            </div>
            <div class="col-xs-12 col-sm-9 content">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><a href="javascript:void(0);" class="toggle-sidebar"><span
                                class="fa fa-angle-double-left" data-toggle="offcanvas"
                                title="Maximize Panel"></span></a>{% block panel_title %}{% endblock %}</h3>
                    </div>
                    <div class="panel-body">
                        {% block info %}{% endblock %}
                    </div><!-- panel body -->
                </div>
            </div><!-- content -->
        </div>
    </div>
    <!--footer-->

{% endblock %}

apps/templates/common/page.html
{% macro pager(data, url) -%}
{% if data %}
<ul class="pagination">
    <li><a href="{{ url_for(url, page=1) }}">首页</a></li>

    {% if data.has_prev %}
    <li><a class="list-group-item active" href="{{ url_for(url, page=data.prev_num) }}">上一页</a></li>
    {% else %}
    <li class="disabled"><a href="#">上一页</a></li>
    {% endif %}

    {% for v in data.iter_pages() %}
        {% if v == data.page %}
        <li><a class="list-group-item active">{{ v }}</a></li>
        {% else %}
        <li><a href="{{ url_for(url, page=v) }}">{{ v }}</a></li>
        {% endif %}
    {% endfor %}

    {% if data.has_next %}
        <li><a class="list-group-item active" href="{{ url_for(url, page=data.next_num) }}">下一页</a></li>
    {% else %}
        <li class="disabled"><a href="#">下一页</a></li>
    {% endif %}

    <li><a href="{{ url_for(url, page=data.pages) }}">尾页</a></li>
</ul>
{% endif %}
{%- endmacro %}

apps/templates/data_analysis/index.html
{% extends '/common/index_base.html' %}

{% block head %}
    <script type="text/javascript" src="{{ url_for('static',filename='echarts/echarts.min.js') }}"></script>
    <meta name="csrf-token" content="{{ csrf_token() }}">
{% endblock %}

{% block title %}
图表分析
{% endblock  %}
{% block panel_title%}
图表分析
{% endblock %}
{% block info %}
 <div class="content-row">
  <!-- 为ECharts准备一个具备大小（宽高）的Dom -->
    <div id="main" class="col-lg-12" style='height:600px'></div>
  
</div>
{% endblock  %}

{% block script %}
  <script type="text/javascript">
    $(function(){
        init_data()
    })

    function init_data(){
        var csrftoken = $("meta[name=csrf-token]").attr("content");
        var user =''
        var code_num=''
        var data =''
        $.ajax({
            url:'/charts/',
            headers: {"X-CSRFToken": csrftoken},
            type:'POST',
            success:function(rs){
                user = rs.user
                code_num = rs.code_num
                data = rs.data



 // 基于准备好的dom，初始化echarts实例
        var myChart = echarts.init(document.getElementById('main'));

        // 指定图表的配置项和数据
        var colors = ['#5793f3', '#d14a61'];
        myChart.title='学员代码量分析';
        var option = {
            title: {
                text: '折线图堆叠'
            },
            tooltip: {
                trigger: 'axis'
            },
            legend: {
                data:user
            },
    
            toolbox: {
                feature: {
                    saveAsImage: {}
                }
            },
            xAxis: {
                type: 'category',
                data: data
            },
            yAxis: {
                type: 'value'
            },
            series: [
                {
                    name:user[0],
                    type:'line',
            
                    data:code_num[0],
                         smooth: true
                },
                {
                    name:user[1],
                    type:'line',
            
                    data:code_num[1],
                         smooth: true
                }
            ]
        };
        // 使用刚指定的配置项和数据显示图表。
        myChart.setOption(option);



            }
        })



    
        
    }
       
    </script>
{% endblock %}

apps/templates/index_base.html
{% extends 'base.html' %}
{% block container %}
    <!--nav-->
    <nav role="navigation" class="navbar navbar-custom">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">

                <a href="#" class="navbar-brand">Feelings's System</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div id="bs-content-row-navbar-collapse-5" class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            {% if session.nick %}
                                {{session.nick}}
                            {% endif %}
                            <b class="caret"></b>
                        </a>
                        <ul role="menu" class="dropdown-menu">
                            <li class="dropdown-header">Setting</li>
                            <li><a href="#">Action</a></li>
                            <li class="divider"></li>
                            <li class="active"><a href="#">Separated link</a></li>
                            <li class="divider"></li>
                            <li class="disabled"><a href="{{ url_for('user.logout') }}">Signout</a></li>
                        </ul>
                    </li>
                </ul>

            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
    <!--header-->
    <div class="container-fluid">
        <!--documents-->
        <div class="row row-offcanvas row-offcanvas-left">
            <div class="col-xs-6 col-sm-3 sidebar-offcanvas" role="navigation">
                <ul class="list-group panel">
                        <li class="list-group-item"><i class="glyphicon glyphicon-align-justify"></i> <b>功能菜单</b></li>
                    <li class="list-group-item"><input type="text" class="form-control search-query"
                                                       placeholder="Search Something"></li>
                    <li class="list-group-item"><a href="{{ url_for('user.personal') }}"><i class="glyphicon glyphicon-home"></i>个人主页
                    </a></li>
                       <li class="list-group-item"><a href="{{ url_for('qd.qd') }}"><i class="glyphicon glyphicon-bell"></i>个人签到</a>
                    <li class="list-group-item"><a href="{{ url_for('user.get_user')}}"><i class="glyphicon glyphicon-certificate"></i>用户管理
                    </a></li>
                    <li class="list-group-item"><a href="list.html"><i class="glyphicon glyphicon-th-list"></i>Tables
                        and List </a></li>
                    <li class="list-group-item"><a href="forms.html"><i
                            class="glyphicon glyphicon-list-alt"></i>Forms</a></li>

                    </li>
                    <li class="list-group-item"><a href="timeline.html"><i class="glyphicon glyphicon-indent-left"></i>Timeline</a>
                    </li>
                    <li class="list-group-item"><a href="calendars.html"><i class="glyphicon glyphicon-calendar"></i>Calendars</a>
                    </li>
                    <li class="list-group-item"><a href="typography.html"><i class="glyphicon glyphicon-font"></i>Typography</a>
                    </li>
                    <li class="list-group-item"><a href="footers.html"><i class="glyphicon glyphicon-minus"></i>Footers</a>
                    </li>
                    <li class="list-group-item"><a href="panels.html"><i class="glyphicon glyphicon-list-alt"></i>Panels</a>
                    </li>
                    <li class="list-group-item"><a href="navs.html"><i class="glyphicon glyphicon-th-list"></i>Navs</a>
                    </li>
                    <li class="list-group-item"><a href="colors.html"><i class="glyphicon glyphicon-tint"></i>Colors</a>
                    </li>
                    <li class="list-group-item"><a href="flex.html"><i class="glyphicon glyphicon-th"></i>Flex</a></li>
                    <li class="list-group-item"><a href="login.html"><i class="glyphicon glyphicon-lock"></i>Login</a>
                    </li>
                    <li>
                        <a href="#demo3" class="list-group-item " data-toggle="collapse">Item 3 <span
                                class="glyphicon glyphicon-chevron-right"></span></a>
                        <div class="collapse" id="demo3">
                            <a href="#SubMenu1" class="list-group-item" data-toggle="collapse">Subitem 1 <span
                                    class="glyphicon glyphicon-chevron-right"></span></a>
                            <div class="collapse list-group-submenu" id="SubMenu1">
                                <a href="#" class="list-group-item">Subitem 1 a</a>
                                <a href="#" class="list-group-item">Subitem 2 b</a>
                                <a href="#SubSubMenu1" class="list-group-item" data-toggle="collapse">Subitem 3 c <span
                                        class="glyphicon glyphicon-chevron-right"></span></a>
                                <div class="collapse list-group-submenu list-group-submenu-1" id="SubSubMenu1">
                                    <a href="#" class="list-group-item">Sub sub item 1</a>
                                    <a href="#" class="list-group-item">Sub sub item 2</a>
                                </div>
                                <a href="#" class="list-group-item">Subitem 4 d</a>
                            </div>
                            <a href="javascript:;" class="list-group-item">Subitem 2</a>
                            <a href="javascript:;" class="list-group-item">Subitem 3</a>
                        </div>
                    </li>
                    <li>
                        <a href="#demo4" class="list-group-item " data-toggle="collapse">Item 4 <span
                                class="glyphicon glyphicon-chevron-right"></span></a>
                    <li class="collapse" id="demo4">
                        <a href="" class="list-group-item">Subitem 1</a>
                        <a href="" class="list-group-item">Subitem 2</a>
                        <a href="" class="list-group-item">Subitem 3</a>
                    </li>
                    </li>
                </ul>
            </div>
            <div class="col-xs-12 col-sm-9 content">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><a href="javascript:void(0);" class="toggle-sidebar"><span
                                class="fa fa-angle-double-left" data-toggle="offcanvas"
                                title="Maximize Panel"></span></a>{% block panel_title %}{% endblock %}</h3>
                    </div>
                    <div class="panel-body">
                        {% block info %}{% endblock %}
                    </div><!-- panel body -->
                </div>
            </div><!-- content -->
        </div>
    </div>
    <!--footer-->

{% endblock %}

apps/templates/user/manager.html
{% extends '/common/index_base.html' %}
{% import "/common/page.html" as pg %}
{% block title %}
    用户管理
{% endblock %}
{% block head %}
    <meta name="csrf-token" content="{{ csrf_token() }}">
{% endblock %}
{% block panel_title %}
    用户管理
{% endblock %}
{% block info %}
    <div class="content-row">
        <button type="button" class="btn btn-info btn-block" data-toggle="tooltip" data-placement="top" title=""
                data-original-title="Tooltip on top">用户信息
        </button>
        <table class="table table-bordered">
            <tr>
                <td>编号</td>
                <td>班级</td>
                <td>姓名</td>
                <td>性别</td>
                <td>角色</td>
                <td>密码</td>
                <td>操作</td>
            </tr>

            {% for u in pager.items %}
                <form id='form{{loop.index}}'>
                <tr>
                    <td>{{ loop.index }}</td>
                    
                    <td>
                        <input name='uid' type="hidden" value='{{ u.id }}'/>
                        <select name="cid" class="form-control">
                        {% for c in clazzs %}
                            <option value="{{ c.id }}"  {% if u.clazzs[0].id == c.id %}selected{% endif %} >{{ c.name }}</option>
                        {% endfor %}
                        </select>
                    </td>
                    <td><input name="nick_name" class="form-control" value="{{ u.nick_name }}"></td>
                    <td><select name="sex" class="form-control">
                        <option value="0" {% if u.sex == '0' %}selected{% endif %}>男</option>
                        <option value="1" {% if u.sex == '1' %}selected{% endif %}>女</option>
                    </select></td>
                    <td><select name="rid" class="form-control">
                        <option value="0" {% if u.rid == 0 %}selected{% endif %}>管理员</option>
                        <option value="1" {% if u.rid == 1 %}selected{% endif %}>普通用户</option>
                    </select></td>
                    <td><a class="btn btn-danger" href="{{ url_for('user.reset_pwd',uid=u.id) }}">密码重置</a></td>
                    <td><a class="btn btn-info" id='{{ loop.index}}' onclick="do_change(this)" href="javascript:void(0)">保 存</a></td>
                </tr>
            </form>
            {% endfor %}
        </table>
        {{ pg.pager(pager, 'user.get_user') }}
    </div>
<div id="mo" class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="gridSystemModalLabel">
  <div class="modal-dialog modal-sm" role="document">

    <div class="alert alert-info alert-dismissable">       
            <strong id='msg'>ceshi</strong> 
    </div>

  </div>
</div>
{% endblock %}
{% block script %}
<script>
    function do_change(btn){
        var csrftoken = $("meta[name=csrf-token]").attr("content");
        index = btn.id
        data = $('#form'+index).serializeArray()
        $.ajax({
            url:'/change_user/',
            data:data,
            method: 'POST',
            headers: {"X-CSRFToken": csrftoken},
            success:function(e){
                if(e.status == 1){
                    $('#msg').text(e.msg)
                    $('#mo').modal('show')
                }
            }
        })
    }

</script>
{% endblock %}